//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semiodesk.Trinity.OntologyGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semiodesk.Trinity.OntologyGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // Attention: This file is generated. Any modifications will eventually be overwritten.
        ///// Date: {0}
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using Semiodesk.Trinity;
        ///
        ///namespace {2}
        ///{{
        ///	{1}
        ///}} ähnelt.
        /// </summary>
        internal static string FileTemplate {
            get {
                return ResourceManager.GetString("FileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        //////&lt;summary&gt;
        //////{3}
        //////{4}
        //////&lt;/summary&gt;
        ///public class {0} : Ontology
        ///{{
        ///    public static readonly Uri Namespace = new Uri(&quot;{1}&quot;);
        ///    public static Uri GetNamespace() {{ return Namespace; }}
        ///    
        ///    public static readonly string Prefix = &quot;{0}&quot;;
        ///    public static string GetPrefix() {{ return Prefix; }} {2}
        ///}}
        /// ähnelt.
        /// </summary>
        internal static string OntologyTemplate {
            get {
                return ResourceManager.GetString("OntologyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die     
        ///
        ///    ///&lt;summary&gt;
        ///    ///{3}
        ///    ///&lt;/summary&gt;
        ///    public static readonly {0} {1} = new {0}(new Uri(&quot;{2}&quot;)); ähnelt.
        /// </summary>
        internal static string ResourceTemplate {
            get {
                return ResourceManager.GetString("ResourceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ///&lt;summary&gt;
        //////{3}
        //////{4}
        //////&lt;/summary&gt;
        ///public static class {0}
        ///{{
        ///    public static readonly Uri Namespace = new Uri(&quot;{1}&quot;);
        ///    public static Uri GetNamespace() {{ return Namespace; }}
        ///    
        ///    public static readonly string Prefix = &quot;{0}&quot;;
        ///    public static string GetPrefix() {{ return Prefix; }} {2}
        ///}} ähnelt.
        /// </summary>
        internal static string StringOntologyTemplate {
            get {
                return ResourceManager.GetString("StringOntologyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///    ///&lt;summary&gt;
        ///    ///{3}
        ///    ///&lt;/summary&gt;
        ///    public const string {1} = &quot;{2}&quot;; ähnelt.
        /// </summary>
        internal static string StringTemplate {
            get {
                return ResourceManager.GetString("StringTemplate", resourceCulture);
            }
        }
    }
}
