// LICENSE:
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// AUTHORS:
//
//  Moritz Eberl <moritz@semiodesk.com>
//  Sebastian Faubel <sebastian@semiodesk.com>
//
// Copyright (c) Semiodesk GmbH

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using VDS.RDF;
using VDS.RDF.Parsing;

namespace Semiodesk.Trinity.Vocabulary
{
    /// <summary>
    /// Parses RDF vocabularies and emits the C# classes that <c>OntologyDiscovery</c> finds at runtime.
    /// </summary>
    /// <remarks>
    /// The emitted shape is dictated by reflection, not by an interface: <c>OntologyDiscovery</c> requires
    /// a class deriving <b>directly</b> from <c>Ontology</c>, with a public parameterless constructor and
    /// static fields named exactly <c>Prefix</c> and <c>Namespace</c>. Nothing enforces that at compile
    /// time, so changing the emission silently breaks discovery — the round-trip test is the only guard.
    /// </remarks>
    public sealed class VocabularyGenerator
    {
        #region Members

        /// <summary>
        /// Marks emitted classes as generated by this tool.
        /// </summary>
        /// <remarks>
        /// Not cosmetic. The TRIN006 analyzer validates <c>[RdfProperty]</c> URIs only against
        /// vocabularies carrying this marker, because only a generated vocabulary is known to be
        /// *complete* — validating against a partially hand-written one would flag correct URIs. The
        /// version is deliberately coarse so regeneration does not churn on every patch release.
        /// </remarks>
        internal const string GeneratedCodeAttribute =
            "[System.CodeDom.Compiler.GeneratedCode(\"trinity-vocab\", \"2.0\")]";

        private const string Rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
        private const string Rdfs = "http://www.w3.org/2000/01/rdf-schema#";
        private const string Owl = "http://www.w3.org/2002/07/owl#";

        /// <summary>
        /// Types whose instances are emitted as <c>Property</c>. Reproduced from 1.x, including the OWL
        /// property characteristics.
        /// </summary>
        private static readonly HashSet<string> PropertyTypes = new HashSet<string>(StringComparer.Ordinal)
        {
            Rdf + "Property",
            Owl + "DatatypeProperty", Owl + "ObjectProperty", Owl + "AnnotationProperty",
            Owl + "AsymmetricProperty", Owl + "DeprecatedProperty", Owl + "FunctionalProperty",
            Owl + "InverseFunctionalProperty", Owl + "IrreflexiveProperty", Owl + "ReflexiveProperty",
            Owl + "SymmetricProperty", Owl + "TransitiveProperty", Owl + "OntologyProperty"
        };

        /// <summary>Types whose instances are emitted as <c>Class</c>.</summary>
        private static readonly HashSet<string> ClassTypes = new HashSet<string>(StringComparer.Ordinal)
        {
            Rdfs + "Class", Owl + "Class"
        };

        #endregion

        #region Methods

        /// <summary>
        /// Generates one C# file covering every vocabulary in the document.
        /// </summary>
        /// <param name="document">What to generate and where it belongs.</param>
        /// <returns>The C# source.</returns>
        public string Generate(VocabularyDocument document)
        {
            if (document == null)
            {
                throw new ArgumentNullException(nameof(document));
            }

            var source = new StringBuilder();

            source.AppendLine("// <auto-generated/>");
            source.AppendLine("// Generated by trinity-vocab from the RDF vocabularies listed in the manifest.");
            source.AppendLine("// Changes will be overwritten the next time it runs.");
            source.AppendLine();
            // Vocabulary classes are named after their prefix, which is conventionally lowercase.
            source.AppendLine("#pragma warning disable CS8981 // lowercase type name");
            source.AppendLine();
            source.AppendLine("using System;");
            source.AppendLine("using Semiodesk.Trinity;");
            source.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(document.Namespace);

            if (hasNamespace)
            {
                source.Append("namespace ").AppendLine(document.Namespace);
                source.AppendLine("{");
            }

            bool first = true;

            foreach (VocabularySource vocabulary in document.Vocabularies)
            {
                if (!first)
                {
                    source.AppendLine();
                }

                first = false;

                Render(source, vocabulary, hasNamespace ? "    " : string.Empty);
            }

            if (hasNamespace)
            {
                source.AppendLine("}");
            }

            source.AppendLine();
            source.AppendLine("#pragma warning restore CS8981");

            return source.ToString();
        }

        /// <summary>
        /// Reads the terms of one vocabulary, sorted for deterministic output.
        /// </summary>
        /// <param name="vocabulary">The vocabulary to read.</param>
        /// <returns>Its terms, ordered by URI.</returns>
        public IReadOnlyList<VocabularyTerm> ReadTerms(VocabularySource vocabulary)
        {
            if (vocabulary == null)
            {
                throw new ArgumentNullException(nameof(vocabulary));
            }

            ITripleStore store = Load(vocabulary.File);

            // Every IRI subject is a candidate, exactly as 1.x did. Restricting to the declared namespace
            // would be tidier but would drop terms the existing vocabularies (and the tests that use
            // them) rely on.
            var subjects = new Dictionary<string, Uri>(StringComparer.Ordinal);
            var types = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
            var comments = new Dictionary<string, string>(StringComparer.Ordinal);

            foreach (IGraph graph in store.Graphs)
            {
                foreach (Triple triple in graph.Triples)
                {
                    if (!(triple.Subject is IUriNode subject))
                    {
                        continue;
                    }

                    string key = subject.Uri.OriginalString;
                    subjects[key] = subject.Uri;

                    string predicate = (triple.Predicate as IUriNode)?.Uri.OriginalString;

                    if (predicate == Rdf + "type" && triple.Object is IUriNode typeNode)
                    {
                        if (!types.TryGetValue(key, out HashSet<string> set))
                        {
                            set = new HashSet<string>(StringComparer.Ordinal);
                            types.Add(key, set);
                        }

                        set.Add(typeNode.Uri.OriginalString);
                    }
                    else if (predicate == Rdfs + "comment" && triple.Object is ILiteralNode comment &&
                             !comments.ContainsKey(key))
                    {
                        comments[key] = comment.Value;
                    }
                }
            }

            var identifiers = new VocabularyIdentifier(vocabulary.Uri, vocabulary.Prefix);
            var result = new List<VocabularyTerm>();

            // Ordinal ordering on the URI makes the output stable across runs and platforms, which also
            // makes the collision suffixes stable.
            foreach (string key in subjects.Keys.OrderBy(k => k, StringComparer.Ordinal))
            {
                string name = identifiers.Next(subjects[key]);

                if (string.IsNullOrEmpty(name))
                {
                    continue;
                }

                types.TryGetValue(key, out HashSet<string> termTypes);
                comments.TryGetValue(key, out string termComment);

                result.Add(new VocabularyTerm(name, subjects[key], Classify(termTypes), termComment));
            }

            return result;
        }

        private void Render(StringBuilder source, VocabularySource vocabulary, string indent)
        {
            IReadOnlyList<VocabularyTerm> terms = ReadTerms(vocabulary);
            string inner = indent + "    ";

            // The typed vocabulary class. OntologyDiscovery requires it to derive directly from Ontology,
            // to have a parameterless constructor, and to expose Prefix and Namespace as static fields.
            source.Append(indent).AppendLine(GeneratedCodeAttribute);
            source.Append(indent).Append("public class ").Append(vocabulary.Prefix).AppendLine(" : Ontology");
            source.Append(indent).AppendLine("{");
            source.Append(inner).Append("public static readonly Uri Namespace = new Uri(\"")
                .Append(vocabulary.Uri.OriginalString).AppendLine("\");");
            source.Append(inner).AppendLine("public static Uri GetNamespace() { return Namespace; }");
            source.AppendLine();
            source.Append(inner).Append("public static readonly string Prefix = \"")
                .Append(vocabulary.Prefix).AppendLine("\";");
            source.Append(inner).AppendLine("public static string GetPrefix() { return Prefix; }");

            foreach (VocabularyTerm term in terms)
            {
                source.AppendLine();
                AppendComment(source, inner, term.Comment);
                source.Append(inner).Append("public static readonly ").Append(term.Kind).Append(' ')
                    .Append(term.Name).Append(" = new ").Append(term.Kind).Append("(new Uri(\"")
                    .Append(term.Uri.OriginalString).AppendLine("\"));");
            }

            source.Append(indent).AppendLine("}");
            source.AppendLine();

            // The string companion. Its const fields are what the TRIN006 analyzer reads to validate
            // [RdfProperty] URIs, since a const is available as IFieldSymbol.ConstantValue with no parsing.
            source.Append(indent).AppendLine(GeneratedCodeAttribute);
            source.Append(indent).Append("public static class ").AppendLine(vocabulary.Prefix.ToUpperInvariant());
            source.Append(indent).AppendLine("{");
            source.Append(inner).Append("public const string Namespace = \"")
                .Append(vocabulary.Uri.OriginalString).AppendLine("\";");
            source.Append(inner).Append("public const string Prefix = \"")
                .Append(vocabulary.Prefix).AppendLine("\";");

            foreach (VocabularyTerm term in terms)
            {
                source.AppendLine();
                AppendComment(source, inner, term.Comment);
                source.Append(inner).Append("public const string ").Append(term.Name).Append(" = \"")
                    .Append(term.Uri.OriginalString).AppendLine("\";");
            }

            source.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// Writes an <c>rdfs:comment</c> as a doc comment, XML-escaped. The 1.x generator did not escape,
        /// so a comment containing &lt; or &amp; produced a malformed XML doc.
        /// </summary>
        private static void AppendComment(StringBuilder source, string indent, string comment)
        {
            if (string.IsNullOrEmpty(comment))
            {
                return;
            }

            source.Append(indent).AppendLine("/// <summary>");

            foreach (string line in comment.Replace("\r\n", "\n").Split('\n'))
            {
                source.Append(indent).Append("/// ").AppendLine(SecurityElement.Escape(line.Trim()));
            }

            source.Append(indent).AppendLine("/// </summary>");
        }

        private static string Classify(HashSet<string> types)
        {
            if (types == null)
            {
                return "Resource";
            }

            if (types.Any(t => PropertyTypes.Contains(t)))
            {
                return "Property";
            }

            if (types.Any(t => ClassTypes.Contains(t)))
            {
                return "Class";
            }

            return "Resource";
        }

        /// <summary>
        /// Loads any RDF file, whether its format carries one graph or a whole dataset.
        /// </summary>
        private static ITripleStore Load(string path)
        {
            if (!File.Exists(path))
            {
                throw new FileNotFoundException("Vocabulary file not found: " + path, path);
            }

            var store = new TripleStore();
            string extension = Path.GetExtension(path);

            try
            {
                // TriG and N-Quads carry named graphs, so they need a store parser.
                IStoreReader storeReader = MimeTypesHelper.GetStoreParserByFileExtension(extension);

                storeReader.Load(store, path);
            }
            catch (RdfParserSelectionException)
            {
                var graph = new Graph();

                FileLoader.Load(graph, path);

                store.Add(graph);
            }

            return store;
        }

        #endregion
    }
}
