// <auto-generated/>
// Generated by trinity-vocab from dces.ttl.
// Changes will be overwritten the next time it runs.

#pragma warning disable CS8981 // lowercase type name

using System;
using Semiodesk.Trinity;

namespace Semiodesk.Trinity.Ontologies
{
    [System.CodeDom.Compiler.GeneratedCode("trinity-vocab", "2.0")]
    public class dces : Ontology
    {
        public static readonly Uri Namespace = new Uri("http://purl.org/dc/elements/1.1/");
        public static Uri GetNamespace() { return Namespace; }

        public static readonly string Prefix = "dces";
        public static string GetPrefix() { return Prefix; }

        /// <summary>
        /// An entity responsible for making contributions to the resource.
        /// </summary>
        public static readonly Property contributor = new Property(new Uri("http://purl.org/dc/elements/1.1/contributor"));

        /// <summary>
        /// The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.
        /// </summary>
        public static readonly Property coverage = new Property(new Uri("http://purl.org/dc/elements/1.1/coverage"));

        /// <summary>
        /// An entity primarily responsible for making the resource.
        /// </summary>
        public static readonly Property creator = new Property(new Uri("http://purl.org/dc/elements/1.1/creator"));

        /// <summary>
        /// A point or period of time associated with an event in the lifecycle of the resource.
        /// </summary>
        public static readonly Property date = new Property(new Uri("http://purl.org/dc/elements/1.1/date"));

        /// <summary>
        /// An account of the resource.
        /// </summary>
        public static readonly Property description = new Property(new Uri("http://purl.org/dc/elements/1.1/description"));

        /// <summary>
        /// The file format, physical medium, or dimensions of the resource.
        /// </summary>
        public static readonly Property format = new Property(new Uri("http://purl.org/dc/elements/1.1/format"));

        /// <summary>
        /// An unambiguous reference to the resource within a given context.
        /// </summary>
        public static readonly Property identifier = new Property(new Uri("http://purl.org/dc/elements/1.1/identifier"));

        /// <summary>
        /// A language of the resource.
        /// </summary>
        public static readonly Property language = new Property(new Uri("http://purl.org/dc/elements/1.1/language"));

        /// <summary>
        /// An entity responsible for making the resource available.
        /// </summary>
        public static readonly Property publisher = new Property(new Uri("http://purl.org/dc/elements/1.1/publisher"));

        /// <summary>
        /// A related resource.
        /// </summary>
        public static readonly Property relation = new Property(new Uri("http://purl.org/dc/elements/1.1/relation"));

        /// <summary>
        /// Information about rights held in and over the resource.
        /// </summary>
        public static readonly Property rights = new Property(new Uri("http://purl.org/dc/elements/1.1/rights"));

        /// <summary>
        /// A related resource from which the described resource is derived.
        /// </summary>
        public static readonly Property source = new Property(new Uri("http://purl.org/dc/elements/1.1/source"));

        /// <summary>
        /// The topic of the resource.
        /// </summary>
        public static readonly Property subject = new Property(new Uri("http://purl.org/dc/elements/1.1/subject"));

        /// <summary>
        /// A name given to the resource.
        /// </summary>
        public static readonly Property title = new Property(new Uri("http://purl.org/dc/elements/1.1/title"));

        /// <summary>
        /// The nature or genre of the resource.
        /// </summary>
        public static readonly Property type = new Property(new Uri("http://purl.org/dc/elements/1.1/type"));
    }

    [System.CodeDom.Compiler.GeneratedCode("trinity-vocab", "2.0")]
    public static class DCES
    {
        public const string Namespace = "http://purl.org/dc/elements/1.1/";
        public const string Prefix = "dces";

        /// <summary>
        /// An entity responsible for making contributions to the resource.
        /// </summary>
        public const string contributor = "http://purl.org/dc/elements/1.1/contributor";

        /// <summary>
        /// The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.
        /// </summary>
        public const string coverage = "http://purl.org/dc/elements/1.1/coverage";

        /// <summary>
        /// An entity primarily responsible for making the resource.
        /// </summary>
        public const string creator = "http://purl.org/dc/elements/1.1/creator";

        /// <summary>
        /// A point or period of time associated with an event in the lifecycle of the resource.
        /// </summary>
        public const string date = "http://purl.org/dc/elements/1.1/date";

        /// <summary>
        /// An account of the resource.
        /// </summary>
        public const string description = "http://purl.org/dc/elements/1.1/description";

        /// <summary>
        /// The file format, physical medium, or dimensions of the resource.
        /// </summary>
        public const string format = "http://purl.org/dc/elements/1.1/format";

        /// <summary>
        /// An unambiguous reference to the resource within a given context.
        /// </summary>
        public const string identifier = "http://purl.org/dc/elements/1.1/identifier";

        /// <summary>
        /// A language of the resource.
        /// </summary>
        public const string language = "http://purl.org/dc/elements/1.1/language";

        /// <summary>
        /// An entity responsible for making the resource available.
        /// </summary>
        public const string publisher = "http://purl.org/dc/elements/1.1/publisher";

        /// <summary>
        /// A related resource.
        /// </summary>
        public const string relation = "http://purl.org/dc/elements/1.1/relation";

        /// <summary>
        /// Information about rights held in and over the resource.
        /// </summary>
        public const string rights = "http://purl.org/dc/elements/1.1/rights";

        /// <summary>
        /// A related resource from which the described resource is derived.
        /// </summary>
        public const string source = "http://purl.org/dc/elements/1.1/source";

        /// <summary>
        /// The topic of the resource.
        /// </summary>
        public const string subject = "http://purl.org/dc/elements/1.1/subject";

        /// <summary>
        /// A name given to the resource.
        /// </summary>
        public const string title = "http://purl.org/dc/elements/1.1/title";

        /// <summary>
        /// The nature or genre of the resource.
        /// </summary>
        public const string type = "http://purl.org/dc/elements/1.1/type";
    }
}

#pragma warning restore CS8981
