// <auto-generated/>
// Generated by trinity-vocab from the RDF vocabularies listed in the manifest.
// Changes will be overwritten the next time it runs.

#pragma warning disable CS8981 // lowercase type name

using System;
using Semiodesk.Trinity;

namespace Semiodesk.Trinity.Ontologies
{
    [System.CodeDom.Compiler.GeneratedCode("trinity-vocab", "2.0")]
    public class dces : Ontology
    {
        public static readonly Uri Namespace = new Uri("http://purl.org/dc/elements/1.1/");
        public static Uri GetNamespace() { return Namespace; }

        public static readonly string Prefix = "dces";
        public static string GetPrefix() { return Prefix; }

        /// <summary>
        /// An entity responsible for making contributions to the resource.
        /// </summary>
        public static readonly Property contributor = new Property(new Uri("http://purl.org/dc/elements/1.1/contributor"));

        /// <summary>
        /// The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.
        /// </summary>
        public static readonly Property coverage = new Property(new Uri("http://purl.org/dc/elements/1.1/coverage"));

        /// <summary>
        /// An entity primarily responsible for making the resource.
        /// </summary>
        public static readonly Property creator = new Property(new Uri("http://purl.org/dc/elements/1.1/creator"));

        /// <summary>
        /// A point or period of time associated with an event in the lifecycle of the resource.
        /// </summary>
        public static readonly Property date = new Property(new Uri("http://purl.org/dc/elements/1.1/date"));

        /// <summary>
        /// An account of the resource.
        /// </summary>
        public static readonly Property description = new Property(new Uri("http://purl.org/dc/elements/1.1/description"));

        /// <summary>
        /// The file format, physical medium, or dimensions of the resource.
        /// </summary>
        public static readonly Property format = new Property(new Uri("http://purl.org/dc/elements/1.1/format"));

        /// <summary>
        /// An unambiguous reference to the resource within a given context.
        /// </summary>
        public static readonly Property identifier = new Property(new Uri("http://purl.org/dc/elements/1.1/identifier"));

        /// <summary>
        /// A language of the resource.
        /// </summary>
        public static readonly Property language = new Property(new Uri("http://purl.org/dc/elements/1.1/language"));

        /// <summary>
        /// An entity responsible for making the resource available.
        /// </summary>
        public static readonly Property publisher = new Property(new Uri("http://purl.org/dc/elements/1.1/publisher"));

        /// <summary>
        /// A related resource.
        /// </summary>
        public static readonly Property relation = new Property(new Uri("http://purl.org/dc/elements/1.1/relation"));

        /// <summary>
        /// Information about rights held in and over the resource.
        /// </summary>
        public static readonly Property rights = new Property(new Uri("http://purl.org/dc/elements/1.1/rights"));

        /// <summary>
        /// A related resource from which the described resource is derived.
        /// </summary>
        public static readonly Property source = new Property(new Uri("http://purl.org/dc/elements/1.1/source"));

        /// <summary>
        /// The topic of the resource.
        /// </summary>
        public static readonly Property subject = new Property(new Uri("http://purl.org/dc/elements/1.1/subject"));

        /// <summary>
        /// A name given to the resource.
        /// </summary>
        public static readonly Property title = new Property(new Uri("http://purl.org/dc/elements/1.1/title"));

        /// <summary>
        /// The nature or genre of the resource.
        /// </summary>
        public static readonly Property type = new Property(new Uri("http://purl.org/dc/elements/1.1/type"));
    }

    [System.CodeDom.Compiler.GeneratedCode("trinity-vocab", "2.0")]
    public static class DCES
    {
        public const string Namespace = "http://purl.org/dc/elements/1.1/";
        public const string Prefix = "dces";

        /// <summary>
        /// An entity responsible for making contributions to the resource.
        /// </summary>
        public const string contributor = "http://purl.org/dc/elements/1.1/contributor";

        /// <summary>
        /// The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.
        /// </summary>
        public const string coverage = "http://purl.org/dc/elements/1.1/coverage";

        /// <summary>
        /// An entity primarily responsible for making the resource.
        /// </summary>
        public const string creator = "http://purl.org/dc/elements/1.1/creator";

        /// <summary>
        /// A point or period of time associated with an event in the lifecycle of the resource.
        /// </summary>
        public const string date = "http://purl.org/dc/elements/1.1/date";

        /// <summary>
        /// An account of the resource.
        /// </summary>
        public const string description = "http://purl.org/dc/elements/1.1/description";

        /// <summary>
        /// The file format, physical medium, or dimensions of the resource.
        /// </summary>
        public const string format = "http://purl.org/dc/elements/1.1/format";

        /// <summary>
        /// An unambiguous reference to the resource within a given context.
        /// </summary>
        public const string identifier = "http://purl.org/dc/elements/1.1/identifier";

        /// <summary>
        /// A language of the resource.
        /// </summary>
        public const string language = "http://purl.org/dc/elements/1.1/language";

        /// <summary>
        /// An entity responsible for making the resource available.
        /// </summary>
        public const string publisher = "http://purl.org/dc/elements/1.1/publisher";

        /// <summary>
        /// A related resource.
        /// </summary>
        public const string relation = "http://purl.org/dc/elements/1.1/relation";

        /// <summary>
        /// Information about rights held in and over the resource.
        /// </summary>
        public const string rights = "http://purl.org/dc/elements/1.1/rights";

        /// <summary>
        /// A related resource from which the described resource is derived.
        /// </summary>
        public const string source = "http://purl.org/dc/elements/1.1/source";

        /// <summary>
        /// The topic of the resource.
        /// </summary>
        public const string subject = "http://purl.org/dc/elements/1.1/subject";

        /// <summary>
        /// A name given to the resource.
        /// </summary>
        public const string title = "http://purl.org/dc/elements/1.1/title";

        /// <summary>
        /// The nature or genre of the resource.
        /// </summary>
        public const string type = "http://purl.org/dc/elements/1.1/type";
    }

    [System.CodeDom.Compiler.GeneratedCode("trinity-vocab", "2.0")]
    public class owl : Ontology
    {
        public static readonly Uri Namespace = new Uri("http://www.w3.org/2002/07/owl#");
        public static Uri GetNamespace() { return Namespace; }

        public static readonly string Prefix = "owl";
        public static string GetPrefix() { return Prefix; }

        /// <summary>
        /// 
        /// This ontology partially describes the built-in classes and
        /// properties that together form the basis of the RDF/XML syntax of OWL 2.
        /// The content of this ontology is based on Tables 6.1 and 6.2
        /// in Section 6.4 of the OWL 2 RDF-Based Semantics specification,
        /// available at http://www.w3.org/TR/owl2-rdf-based-semantics/.
        /// Please note that those tables do not include the different annotations
        /// (labels, comments and rdfs:isDefinedBy links) used in this file.
        /// Also note that the descriptions provided in this ontology do not
        /// provide a complete and correct formal description of either the syntax
        /// or the semantics of the introduced terms (please see the OWL 2
        /// recommendations for the complete and normative specifications).
        /// Furthermore, the information provided by this ontology may be
        /// misleading if not used with care. This ontology SHOULD NOT be imported
        /// into OWL ontologies. Importing this file into an OWL 2 DL ontology
        /// will cause it to become an OWL 2 Full ontology and may have other,
        /// unexpected, consequences.
        /// 
        /// </summary>
        public static readonly Resource owl_0 = new Resource(new Uri("http://www.w3.org/2002/07/owl"));

        /// <summary>
        /// The class of collections of pairwise different individuals.
        /// </summary>
        public static readonly Class AllDifferent = new Class(new Uri("http://www.w3.org/2002/07/owl#AllDifferent"));

        /// <summary>
        /// The class of collections of pairwise disjoint classes.
        /// </summary>
        public static readonly Class AllDisjointClasses = new Class(new Uri("http://www.w3.org/2002/07/owl#AllDisjointClasses"));

        /// <summary>
        /// The class of collections of pairwise disjoint properties.
        /// </summary>
        public static readonly Class AllDisjointProperties = new Class(new Uri("http://www.w3.org/2002/07/owl#AllDisjointProperties"));

        /// <summary>
        /// The class of annotated annotations for which the RDF serialization consists of an annotated subject, predicate and object.
        /// </summary>
        public static readonly Class Annotation = new Class(new Uri("http://www.w3.org/2002/07/owl#Annotation"));

        /// <summary>
        /// The class of annotation properties.
        /// </summary>
        public static readonly Class AnnotationProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#AnnotationProperty"));

        /// <summary>
        /// The class of asymmetric properties.
        /// </summary>
        public static readonly Class AsymmetricProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#AsymmetricProperty"));

        /// <summary>
        /// The class of annotated axioms for which the RDF serialization consists of an annotated subject, predicate and object.
        /// </summary>
        public static readonly Class Axiom = new Class(new Uri("http://www.w3.org/2002/07/owl#Axiom"));

        /// <summary>
        /// The class of OWL classes.
        /// </summary>
        public static readonly Class Class = new Class(new Uri("http://www.w3.org/2002/07/owl#Class"));

        /// <summary>
        /// The class of OWL data ranges, which are special kinds of datatypes. Note: The use of the IRI owl:DataRange has been deprecated as of OWL 2. The IRI rdfs:Datatype SHOULD be used instead.
        /// </summary>
        public static readonly Class DataRange = new Class(new Uri("http://www.w3.org/2002/07/owl#DataRange"));

        /// <summary>
        /// The class of data properties.
        /// </summary>
        public static readonly Class DatatypeProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#DatatypeProperty"));

        /// <summary>
        /// The class of deprecated classes.
        /// </summary>
        public static readonly Class DeprecatedClass = new Class(new Uri("http://www.w3.org/2002/07/owl#DeprecatedClass"));

        /// <summary>
        /// The class of deprecated properties.
        /// </summary>
        public static readonly Class DeprecatedProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#DeprecatedProperty"));

        /// <summary>
        /// The class of functional properties.
        /// </summary>
        public static readonly Class FunctionalProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#FunctionalProperty"));

        /// <summary>
        /// The class of inverse-functional properties.
        /// </summary>
        public static readonly Class InverseFunctionalProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#InverseFunctionalProperty"));

        /// <summary>
        /// The class of irreflexive properties.
        /// </summary>
        public static readonly Class IrreflexiveProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#IrreflexiveProperty"));

        /// <summary>
        /// The class of named individuals.
        /// </summary>
        public static readonly Class NamedIndividual = new Class(new Uri("http://www.w3.org/2002/07/owl#NamedIndividual"));

        /// <summary>
        /// The class of negative property assertions.
        /// </summary>
        public static readonly Class NegativePropertyAssertion = new Class(new Uri("http://www.w3.org/2002/07/owl#NegativePropertyAssertion"));

        /// <summary>
        /// This is the empty class.
        /// </summary>
        public static readonly Class Nothing = new Class(new Uri("http://www.w3.org/2002/07/owl#Nothing"));

        /// <summary>
        /// The class of object properties.
        /// </summary>
        public static readonly Class ObjectProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#ObjectProperty"));

        /// <summary>
        /// The class of ontologies.
        /// </summary>
        public static readonly Class Ontology = new Class(new Uri("http://www.w3.org/2002/07/owl#Ontology"));

        /// <summary>
        /// The class of ontology properties.
        /// </summary>
        public static readonly Class OntologyProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#OntologyProperty"));

        /// <summary>
        /// The class of reflexive properties.
        /// </summary>
        public static readonly Class ReflexiveProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#ReflexiveProperty"));

        /// <summary>
        /// The class of property restrictions.
        /// </summary>
        public static readonly Class Restriction = new Class(new Uri("http://www.w3.org/2002/07/owl#Restriction"));

        /// <summary>
        /// The class of symmetric properties.
        /// </summary>
        public static readonly Class SymmetricProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#SymmetricProperty"));

        /// <summary>
        /// The class of OWL individuals.
        /// </summary>
        public static readonly Class Thing = new Class(new Uri("http://www.w3.org/2002/07/owl#Thing"));

        /// <summary>
        /// The class of transitive properties.
        /// </summary>
        public static readonly Class TransitiveProperty = new Class(new Uri("http://www.w3.org/2002/07/owl#TransitiveProperty"));

        /// <summary>
        /// The property that determines the class that a universal property restriction refers to.
        /// </summary>
        public static readonly Property allValuesFrom = new Property(new Uri("http://www.w3.org/2002/07/owl#allValuesFrom"));

        /// <summary>
        /// The property that determines the predicate of an annotated axiom or annotated annotation.
        /// </summary>
        public static readonly Property annotatedProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#annotatedProperty"));

        /// <summary>
        /// The property that determines the subject of an annotated axiom or annotated annotation.
        /// </summary>
        public static readonly Property annotatedSource = new Property(new Uri("http://www.w3.org/2002/07/owl#annotatedSource"));

        /// <summary>
        /// The property that determines the object of an annotated axiom or annotated annotation.
        /// </summary>
        public static readonly Property annotatedTarget = new Property(new Uri("http://www.w3.org/2002/07/owl#annotatedTarget"));

        /// <summary>
        /// The property that determines the predicate of a negative property assertion.
        /// </summary>
        public static readonly Property assertionProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#assertionProperty"));

        /// <summary>
        /// The annotation property that indicates that a given ontology is backward compatible with another ontology.
        /// </summary>
        public static readonly Property backwardCompatibleWith = new Property(new Uri("http://www.w3.org/2002/07/owl#backwardCompatibleWith"));

        /// <summary>
        /// The data property that does not relate any individual to any data value.
        /// </summary>
        public static readonly Property bottomDataProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#bottomDataProperty"));

        /// <summary>
        /// The object property that does not relate any two individuals.
        /// </summary>
        public static readonly Property bottomObjectProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#bottomObjectProperty"));

        /// <summary>
        /// The property that determines the cardinality of an exact cardinality restriction.
        /// </summary>
        public static readonly Property cardinality = new Property(new Uri("http://www.w3.org/2002/07/owl#cardinality"));

        /// <summary>
        /// The property that determines that a given class is the complement of another class.
        /// </summary>
        public static readonly Property complementOf = new Property(new Uri("http://www.w3.org/2002/07/owl#complementOf"));

        /// <summary>
        /// The property that determines that a given data range is the complement of another data range with respect to the data domain.
        /// </summary>
        public static readonly Property datatypeComplementOf = new Property(new Uri("http://www.w3.org/2002/07/owl#datatypeComplementOf"));

        /// <summary>
        /// The annotation property that indicates that a given entity has been deprecated.
        /// </summary>
        public static readonly Property deprecated = new Property(new Uri("http://www.w3.org/2002/07/owl#deprecated"));

        /// <summary>
        /// The property that determines that two given individuals are different.
        /// </summary>
        public static readonly Property differentFrom = new Property(new Uri("http://www.w3.org/2002/07/owl#differentFrom"));

        /// <summary>
        /// The property that determines that a given class is equivalent to the disjoint union of a collection of other classes.
        /// </summary>
        public static readonly Property disjointUnionOf = new Property(new Uri("http://www.w3.org/2002/07/owl#disjointUnionOf"));

        /// <summary>
        /// The property that determines that two given classes are disjoint.
        /// </summary>
        public static readonly Property disjointWith = new Property(new Uri("http://www.w3.org/2002/07/owl#disjointWith"));

        /// <summary>
        /// The property that determines the collection of pairwise different individuals in a owl:AllDifferent axiom.
        /// </summary>
        public static readonly Property distinctMembers = new Property(new Uri("http://www.w3.org/2002/07/owl#distinctMembers"));

        /// <summary>
        /// The property that determines that two given classes are equivalent, and that is used to specify datatype definitions.
        /// </summary>
        public static readonly Property equivalentClass = new Property(new Uri("http://www.w3.org/2002/07/owl#equivalentClass"));

        /// <summary>
        /// The property that determines that two given properties are equivalent.
        /// </summary>
        public static readonly Property equivalentProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#equivalentProperty"));

        /// <summary>
        /// The property that determines the collection of properties that jointly build a key.
        /// </summary>
        public static readonly Property hasKey = new Property(new Uri("http://www.w3.org/2002/07/owl#hasKey"));

        /// <summary>
        /// The property that determines the property that a self restriction refers to.
        /// </summary>
        public static readonly Property hasSelf = new Property(new Uri("http://www.w3.org/2002/07/owl#hasSelf"));

        /// <summary>
        /// The property that determines the individual that a has-value restriction refers to.
        /// </summary>
        public static readonly Property hasValue = new Property(new Uri("http://www.w3.org/2002/07/owl#hasValue"));

        /// <summary>
        /// The property that is used for importing other ontologies into a given ontology.
        /// </summary>
        public static readonly Property imports = new Property(new Uri("http://www.w3.org/2002/07/owl#imports"));

        /// <summary>
        /// The annotation property that indicates that a given ontology is incompatible with another ontology.
        /// </summary>
        public static readonly Property incompatibleWith = new Property(new Uri("http://www.w3.org/2002/07/owl#incompatibleWith"));

        /// <summary>
        /// The property that determines the collection of classes or data ranges that build an intersection.
        /// </summary>
        public static readonly Property intersectionOf = new Property(new Uri("http://www.w3.org/2002/07/owl#intersectionOf"));

        /// <summary>
        /// The property that determines that two given properties are inverse.
        /// </summary>
        public static readonly Property inverseOf = new Property(new Uri("http://www.w3.org/2002/07/owl#inverseOf"));

        /// <summary>
        /// The property that determines the cardinality of a maximum cardinality restriction.
        /// </summary>
        public static readonly Property maxCardinality = new Property(new Uri("http://www.w3.org/2002/07/owl#maxCardinality"));

        /// <summary>
        /// The property that determines the cardinality of a maximum qualified cardinality restriction.
        /// </summary>
        public static readonly Property maxQualifiedCardinality = new Property(new Uri("http://www.w3.org/2002/07/owl#maxQualifiedCardinality"));

        /// <summary>
        /// The property that determines the collection of members in either a owl:AllDifferent, owl:AllDisjointClasses or owl:AllDisjointProperties axiom.
        /// </summary>
        public static readonly Property members = new Property(new Uri("http://www.w3.org/2002/07/owl#members"));

        /// <summary>
        /// The property that determines the cardinality of a minimum cardinality restriction.
        /// </summary>
        public static readonly Property minCardinality = new Property(new Uri("http://www.w3.org/2002/07/owl#minCardinality"));

        /// <summary>
        /// The property that determines the cardinality of a minimum qualified cardinality restriction.
        /// </summary>
        public static readonly Property minQualifiedCardinality = new Property(new Uri("http://www.w3.org/2002/07/owl#minQualifiedCardinality"));

        /// <summary>
        /// The property that determines the class that a qualified object cardinality restriction refers to.
        /// </summary>
        public static readonly Property onClass = new Property(new Uri("http://www.w3.org/2002/07/owl#onClass"));

        /// <summary>
        /// The property that determines the data range that a qualified data cardinality restriction refers to.
        /// </summary>
        public static readonly Property onDataRange = new Property(new Uri("http://www.w3.org/2002/07/owl#onDataRange"));

        /// <summary>
        /// The property that determines the datatype that a datatype restriction refers to.
        /// </summary>
        public static readonly Property onDatatype = new Property(new Uri("http://www.w3.org/2002/07/owl#onDatatype"));

        /// <summary>
        /// The property that determines the n-tuple of properties that a property restriction on an n-ary data range refers to.
        /// </summary>
        public static readonly Property onProperties = new Property(new Uri("http://www.w3.org/2002/07/owl#onProperties"));

        /// <summary>
        /// The property that determines the property that a property restriction refers to.
        /// </summary>
        public static readonly Property onProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#onProperty"));

        /// <summary>
        /// The property that determines the collection of individuals or data values that build an enumeration.
        /// </summary>
        public static readonly Property oneOf = new Property(new Uri("http://www.w3.org/2002/07/owl#oneOf"));

        /// <summary>
        /// The annotation property that indicates the predecessor ontology of a given ontology.
        /// </summary>
        public static readonly Property priorVersion = new Property(new Uri("http://www.w3.org/2002/07/owl#priorVersion"));

        /// <summary>
        /// The property that determines the n-tuple of properties that build a sub property chain of a given property.
        /// </summary>
        public static readonly Property propertyChainAxiom = new Property(new Uri("http://www.w3.org/2002/07/owl#propertyChainAxiom"));

        /// <summary>
        /// The property that determines that two given properties are disjoint.
        /// </summary>
        public static readonly Property propertyDisjointWith = new Property(new Uri("http://www.w3.org/2002/07/owl#propertyDisjointWith"));

        /// <summary>
        /// The property that determines the cardinality of an exact qualified cardinality restriction.
        /// </summary>
        public static readonly Property qualifiedCardinality = new Property(new Uri("http://www.w3.org/2002/07/owl#qualifiedCardinality"));

        /// <summary>
        /// The property that determines that two given individuals are equal.
        /// </summary>
        public static readonly Property sameAs = new Property(new Uri("http://www.w3.org/2002/07/owl#sameAs"));

        /// <summary>
        /// The property that determines the class that an existential property restriction refers to.
        /// </summary>
        public static readonly Property someValuesFrom = new Property(new Uri("http://www.w3.org/2002/07/owl#someValuesFrom"));

        /// <summary>
        /// The property that determines the subject of a negative property assertion.
        /// </summary>
        public static readonly Property sourceIndividual = new Property(new Uri("http://www.w3.org/2002/07/owl#sourceIndividual"));

        /// <summary>
        /// The property that determines the object of a negative object property assertion.
        /// </summary>
        public static readonly Property targetIndividual = new Property(new Uri("http://www.w3.org/2002/07/owl#targetIndividual"));

        /// <summary>
        /// The property that determines the value of a negative data property assertion.
        /// </summary>
        public static readonly Property targetValue = new Property(new Uri("http://www.w3.org/2002/07/owl#targetValue"));

        /// <summary>
        /// The data property that relates every individual to every data value.
        /// </summary>
        public static readonly Property topDataProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#topDataProperty"));

        /// <summary>
        /// The object property that relates every two individuals.
        /// </summary>
        public static readonly Property topObjectProperty = new Property(new Uri("http://www.w3.org/2002/07/owl#topObjectProperty"));

        /// <summary>
        /// The property that determines the collection of classes or data ranges that build a union.
        /// </summary>
        public static readonly Property unionOf = new Property(new Uri("http://www.w3.org/2002/07/owl#unionOf"));

        /// <summary>
        /// The property that identifies the version IRI of an ontology.
        /// </summary>
        public static readonly Property versionIRI = new Property(new Uri("http://www.w3.org/2002/07/owl#versionIRI"));

        /// <summary>
        /// The annotation property that provides version information for an ontology or another OWL construct.
        /// </summary>
        public static readonly Property versionInfo = new Property(new Uri("http://www.w3.org/2002/07/owl#versionInfo"));

        /// <summary>
        /// The property that determines the collection of facet-value pairs that define a datatype restriction.
        /// </summary>
        public static readonly Property withRestrictions = new Property(new Uri("http://www.w3.org/2002/07/owl#withRestrictions"));
    }

    [System.CodeDom.Compiler.GeneratedCode("trinity-vocab", "2.0")]
    public static class OWL
    {
        public const string Namespace = "http://www.w3.org/2002/07/owl#";
        public const string Prefix = "owl";

        /// <summary>
        /// 
        /// This ontology partially describes the built-in classes and
        /// properties that together form the basis of the RDF/XML syntax of OWL 2.
        /// The content of this ontology is based on Tables 6.1 and 6.2
        /// in Section 6.4 of the OWL 2 RDF-Based Semantics specification,
        /// available at http://www.w3.org/TR/owl2-rdf-based-semantics/.
        /// Please note that those tables do not include the different annotations
        /// (labels, comments and rdfs:isDefinedBy links) used in this file.
        /// Also note that the descriptions provided in this ontology do not
        /// provide a complete and correct formal description of either the syntax
        /// or the semantics of the introduced terms (please see the OWL 2
        /// recommendations for the complete and normative specifications).
        /// Furthermore, the information provided by this ontology may be
        /// misleading if not used with care. This ontology SHOULD NOT be imported
        /// into OWL ontologies. Importing this file into an OWL 2 DL ontology
        /// will cause it to become an OWL 2 Full ontology and may have other,
        /// unexpected, consequences.
        /// 
        /// </summary>
        public const string owl_0 = "http://www.w3.org/2002/07/owl";

        /// <summary>
        /// The class of collections of pairwise different individuals.
        /// </summary>
        public const string AllDifferent = "http://www.w3.org/2002/07/owl#AllDifferent";

        /// <summary>
        /// The class of collections of pairwise disjoint classes.
        /// </summary>
        public const string AllDisjointClasses = "http://www.w3.org/2002/07/owl#AllDisjointClasses";

        /// <summary>
        /// The class of collections of pairwise disjoint properties.
        /// </summary>
        public const string AllDisjointProperties = "http://www.w3.org/2002/07/owl#AllDisjointProperties";

        /// <summary>
        /// The class of annotated annotations for which the RDF serialization consists of an annotated subject, predicate and object.
        /// </summary>
        public const string Annotation = "http://www.w3.org/2002/07/owl#Annotation";

        /// <summary>
        /// The class of annotation properties.
        /// </summary>
        public const string AnnotationProperty = "http://www.w3.org/2002/07/owl#AnnotationProperty";

        /// <summary>
        /// The class of asymmetric properties.
        /// </summary>
        public const string AsymmetricProperty = "http://www.w3.org/2002/07/owl#AsymmetricProperty";

        /// <summary>
        /// The class of annotated axioms for which the RDF serialization consists of an annotated subject, predicate and object.
        /// </summary>
        public const string Axiom = "http://www.w3.org/2002/07/owl#Axiom";

        /// <summary>
        /// The class of OWL classes.
        /// </summary>
        public const string Class = "http://www.w3.org/2002/07/owl#Class";

        /// <summary>
        /// The class of OWL data ranges, which are special kinds of datatypes. Note: The use of the IRI owl:DataRange has been deprecated as of OWL 2. The IRI rdfs:Datatype SHOULD be used instead.
        /// </summary>
        public const string DataRange = "http://www.w3.org/2002/07/owl#DataRange";

        /// <summary>
        /// The class of data properties.
        /// </summary>
        public const string DatatypeProperty = "http://www.w3.org/2002/07/owl#DatatypeProperty";

        /// <summary>
        /// The class of deprecated classes.
        /// </summary>
        public const string DeprecatedClass = "http://www.w3.org/2002/07/owl#DeprecatedClass";

        /// <summary>
        /// The class of deprecated properties.
        /// </summary>
        public const string DeprecatedProperty = "http://www.w3.org/2002/07/owl#DeprecatedProperty";

        /// <summary>
        /// The class of functional properties.
        /// </summary>
        public const string FunctionalProperty = "http://www.w3.org/2002/07/owl#FunctionalProperty";

        /// <summary>
        /// The class of inverse-functional properties.
        /// </summary>
        public const string InverseFunctionalProperty = "http://www.w3.org/2002/07/owl#InverseFunctionalProperty";

        /// <summary>
        /// The class of irreflexive properties.
        /// </summary>
        public const string IrreflexiveProperty = "http://www.w3.org/2002/07/owl#IrreflexiveProperty";

        /// <summary>
        /// The class of named individuals.
        /// </summary>
        public const string NamedIndividual = "http://www.w3.org/2002/07/owl#NamedIndividual";

        /// <summary>
        /// The class of negative property assertions.
        /// </summary>
        public const string NegativePropertyAssertion = "http://www.w3.org/2002/07/owl#NegativePropertyAssertion";

        /// <summary>
        /// This is the empty class.
        /// </summary>
        public const string Nothing = "http://www.w3.org/2002/07/owl#Nothing";

        /// <summary>
        /// The class of object properties.
        /// </summary>
        public const string ObjectProperty = "http://www.w3.org/2002/07/owl#ObjectProperty";

        /// <summary>
        /// The class of ontologies.
        /// </summary>
        public const string Ontology = "http://www.w3.org/2002/07/owl#Ontology";

        /// <summary>
        /// The class of ontology properties.
        /// </summary>
        public const string OntologyProperty = "http://www.w3.org/2002/07/owl#OntologyProperty";

        /// <summary>
        /// The class of reflexive properties.
        /// </summary>
        public const string ReflexiveProperty = "http://www.w3.org/2002/07/owl#ReflexiveProperty";

        /// <summary>
        /// The class of property restrictions.
        /// </summary>
        public const string Restriction = "http://www.w3.org/2002/07/owl#Restriction";

        /// <summary>
        /// The class of symmetric properties.
        /// </summary>
        public const string SymmetricProperty = "http://www.w3.org/2002/07/owl#SymmetricProperty";

        /// <summary>
        /// The class of OWL individuals.
        /// </summary>
        public const string Thing = "http://www.w3.org/2002/07/owl#Thing";

        /// <summary>
        /// The class of transitive properties.
        /// </summary>
        public const string TransitiveProperty = "http://www.w3.org/2002/07/owl#TransitiveProperty";

        /// <summary>
        /// The property that determines the class that a universal property restriction refers to.
        /// </summary>
        public const string allValuesFrom = "http://www.w3.org/2002/07/owl#allValuesFrom";

        /// <summary>
        /// The property that determines the predicate of an annotated axiom or annotated annotation.
        /// </summary>
        public const string annotatedProperty = "http://www.w3.org/2002/07/owl#annotatedProperty";

        /// <summary>
        /// The property that determines the subject of an annotated axiom or annotated annotation.
        /// </summary>
        public const string annotatedSource = "http://www.w3.org/2002/07/owl#annotatedSource";

        /// <summary>
        /// The property that determines the object of an annotated axiom or annotated annotation.
        /// </summary>
        public const string annotatedTarget = "http://www.w3.org/2002/07/owl#annotatedTarget";

        /// <summary>
        /// The property that determines the predicate of a negative property assertion.
        /// </summary>
        public const string assertionProperty = "http://www.w3.org/2002/07/owl#assertionProperty";

        /// <summary>
        /// The annotation property that indicates that a given ontology is backward compatible with another ontology.
        /// </summary>
        public const string backwardCompatibleWith = "http://www.w3.org/2002/07/owl#backwardCompatibleWith";

        /// <summary>
        /// The data property that does not relate any individual to any data value.
        /// </summary>
        public const string bottomDataProperty = "http://www.w3.org/2002/07/owl#bottomDataProperty";

        /// <summary>
        /// The object property that does not relate any two individuals.
        /// </summary>
        public const string bottomObjectProperty = "http://www.w3.org/2002/07/owl#bottomObjectProperty";

        /// <summary>
        /// The property that determines the cardinality of an exact cardinality restriction.
        /// </summary>
        public const string cardinality = "http://www.w3.org/2002/07/owl#cardinality";

        /// <summary>
        /// The property that determines that a given class is the complement of another class.
        /// </summary>
        public const string complementOf = "http://www.w3.org/2002/07/owl#complementOf";

        /// <summary>
        /// The property that determines that a given data range is the complement of another data range with respect to the data domain.
        /// </summary>
        public const string datatypeComplementOf = "http://www.w3.org/2002/07/owl#datatypeComplementOf";

        /// <summary>
        /// The annotation property that indicates that a given entity has been deprecated.
        /// </summary>
        public const string deprecated = "http://www.w3.org/2002/07/owl#deprecated";

        /// <summary>
        /// The property that determines that two given individuals are different.
        /// </summary>
        public const string differentFrom = "http://www.w3.org/2002/07/owl#differentFrom";

        /// <summary>
        /// The property that determines that a given class is equivalent to the disjoint union of a collection of other classes.
        /// </summary>
        public const string disjointUnionOf = "http://www.w3.org/2002/07/owl#disjointUnionOf";

        /// <summary>
        /// The property that determines that two given classes are disjoint.
        /// </summary>
        public const string disjointWith = "http://www.w3.org/2002/07/owl#disjointWith";

        /// <summary>
        /// The property that determines the collection of pairwise different individuals in a owl:AllDifferent axiom.
        /// </summary>
        public const string distinctMembers = "http://www.w3.org/2002/07/owl#distinctMembers";

        /// <summary>
        /// The property that determines that two given classes are equivalent, and that is used to specify datatype definitions.
        /// </summary>
        public const string equivalentClass = "http://www.w3.org/2002/07/owl#equivalentClass";

        /// <summary>
        /// The property that determines that two given properties are equivalent.
        /// </summary>
        public const string equivalentProperty = "http://www.w3.org/2002/07/owl#equivalentProperty";

        /// <summary>
        /// The property that determines the collection of properties that jointly build a key.
        /// </summary>
        public const string hasKey = "http://www.w3.org/2002/07/owl#hasKey";

        /// <summary>
        /// The property that determines the property that a self restriction refers to.
        /// </summary>
        public const string hasSelf = "http://www.w3.org/2002/07/owl#hasSelf";

        /// <summary>
        /// The property that determines the individual that a has-value restriction refers to.
        /// </summary>
        public const string hasValue = "http://www.w3.org/2002/07/owl#hasValue";

        /// <summary>
        /// The property that is used for importing other ontologies into a given ontology.
        /// </summary>
        public const string imports = "http://www.w3.org/2002/07/owl#imports";

        /// <summary>
        /// The annotation property that indicates that a given ontology is incompatible with another ontology.
        /// </summary>
        public const string incompatibleWith = "http://www.w3.org/2002/07/owl#incompatibleWith";

        /// <summary>
        /// The property that determines the collection of classes or data ranges that build an intersection.
        /// </summary>
        public const string intersectionOf = "http://www.w3.org/2002/07/owl#intersectionOf";

        /// <summary>
        /// The property that determines that two given properties are inverse.
        /// </summary>
        public const string inverseOf = "http://www.w3.org/2002/07/owl#inverseOf";

        /// <summary>
        /// The property that determines the cardinality of a maximum cardinality restriction.
        /// </summary>
        public const string maxCardinality = "http://www.w3.org/2002/07/owl#maxCardinality";

        /// <summary>
        /// The property that determines the cardinality of a maximum qualified cardinality restriction.
        /// </summary>
        public const string maxQualifiedCardinality = "http://www.w3.org/2002/07/owl#maxQualifiedCardinality";

        /// <summary>
        /// The property that determines the collection of members in either a owl:AllDifferent, owl:AllDisjointClasses or owl:AllDisjointProperties axiom.
        /// </summary>
        public const string members = "http://www.w3.org/2002/07/owl#members";

        /// <summary>
        /// The property that determines the cardinality of a minimum cardinality restriction.
        /// </summary>
        public const string minCardinality = "http://www.w3.org/2002/07/owl#minCardinality";

        /// <summary>
        /// The property that determines the cardinality of a minimum qualified cardinality restriction.
        /// </summary>
        public const string minQualifiedCardinality = "http://www.w3.org/2002/07/owl#minQualifiedCardinality";

        /// <summary>
        /// The property that determines the class that a qualified object cardinality restriction refers to.
        /// </summary>
        public const string onClass = "http://www.w3.org/2002/07/owl#onClass";

        /// <summary>
        /// The property that determines the data range that a qualified data cardinality restriction refers to.
        /// </summary>
        public const string onDataRange = "http://www.w3.org/2002/07/owl#onDataRange";

        /// <summary>
        /// The property that determines the datatype that a datatype restriction refers to.
        /// </summary>
        public const string onDatatype = "http://www.w3.org/2002/07/owl#onDatatype";

        /// <summary>
        /// The property that determines the n-tuple of properties that a property restriction on an n-ary data range refers to.
        /// </summary>
        public const string onProperties = "http://www.w3.org/2002/07/owl#onProperties";

        /// <summary>
        /// The property that determines the property that a property restriction refers to.
        /// </summary>
        public const string onProperty = "http://www.w3.org/2002/07/owl#onProperty";

        /// <summary>
        /// The property that determines the collection of individuals or data values that build an enumeration.
        /// </summary>
        public const string oneOf = "http://www.w3.org/2002/07/owl#oneOf";

        /// <summary>
        /// The annotation property that indicates the predecessor ontology of a given ontology.
        /// </summary>
        public const string priorVersion = "http://www.w3.org/2002/07/owl#priorVersion";

        /// <summary>
        /// The property that determines the n-tuple of properties that build a sub property chain of a given property.
        /// </summary>
        public const string propertyChainAxiom = "http://www.w3.org/2002/07/owl#propertyChainAxiom";

        /// <summary>
        /// The property that determines that two given properties are disjoint.
        /// </summary>
        public const string propertyDisjointWith = "http://www.w3.org/2002/07/owl#propertyDisjointWith";

        /// <summary>
        /// The property that determines the cardinality of an exact qualified cardinality restriction.
        /// </summary>
        public const string qualifiedCardinality = "http://www.w3.org/2002/07/owl#qualifiedCardinality";

        /// <summary>
        /// The property that determines that two given individuals are equal.
        /// </summary>
        public const string sameAs = "http://www.w3.org/2002/07/owl#sameAs";

        /// <summary>
        /// The property that determines the class that an existential property restriction refers to.
        /// </summary>
        public const string someValuesFrom = "http://www.w3.org/2002/07/owl#someValuesFrom";

        /// <summary>
        /// The property that determines the subject of a negative property assertion.
        /// </summary>
        public const string sourceIndividual = "http://www.w3.org/2002/07/owl#sourceIndividual";

        /// <summary>
        /// The property that determines the object of a negative object property assertion.
        /// </summary>
        public const string targetIndividual = "http://www.w3.org/2002/07/owl#targetIndividual";

        /// <summary>
        /// The property that determines the value of a negative data property assertion.
        /// </summary>
        public const string targetValue = "http://www.w3.org/2002/07/owl#targetValue";

        /// <summary>
        /// The data property that relates every individual to every data value.
        /// </summary>
        public const string topDataProperty = "http://www.w3.org/2002/07/owl#topDataProperty";

        /// <summary>
        /// The object property that relates every two individuals.
        /// </summary>
        public const string topObjectProperty = "http://www.w3.org/2002/07/owl#topObjectProperty";

        /// <summary>
        /// The property that determines the collection of classes or data ranges that build a union.
        /// </summary>
        public const string unionOf = "http://www.w3.org/2002/07/owl#unionOf";

        /// <summary>
        /// The property that identifies the version IRI of an ontology.
        /// </summary>
        public const string versionIRI = "http://www.w3.org/2002/07/owl#versionIRI";

        /// <summary>
        /// The annotation property that provides version information for an ontology or another OWL construct.
        /// </summary>
        public const string versionInfo = "http://www.w3.org/2002/07/owl#versionInfo";

        /// <summary>
        /// The property that determines the collection of facet-value pairs that define a datatype restriction.
        /// </summary>
        public const string withRestrictions = "http://www.w3.org/2002/07/owl#withRestrictions";
    }
}

#pragma warning restore CS8981
