// LICENSE:
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// AUTHORS:
//
//  Moritz Eberl <moritz@semiodesk.com>
//  Sebastian Faubel <sebastian@semiodesk.com>
//
// Copyright (c) Semiodesk GmbH 2015-2019

using NUnit.Framework;
using System.Reflection;

namespace Semiodesk.Trinity.Tests
{
    /// <summary>
    /// This test needs A LOT work!
    /// </summary>
    [TestFixture]
    public class OntologyTest
    {
        [Test]
        public void TestDiscovery()
        {
            OntologyDiscovery.AddAssembly(Assembly.GetExecutingAssembly());
            var l = OntologyDiscovery.Classes;
        }

        /// <summary>
        /// Hand-written and generated vocabularies are discovered the same way, from the same assembly.
        /// </summary>
        /// <remarks>
        /// The point of this test is that the generator is <b>optional</b>. This project has 28 hand-written
        /// vocabulary classes and two generated ones (`dces` and `owl`, from
        /// <c>Ontologies/vocabularies.json</c>); <c>OntologyDiscovery</c> cannot tell them apart, because it
        /// only looks for the convention. Nothing in Trinity requires generated vocabulary, and this asserts
        /// that both routes stay first-class.
        /// </remarks>
        [Test]
        public void DiscoversHandWrittenAndGeneratedVocabulariesAlike()
        {
            OntologyDiscovery.AddAssembly(Assembly.GetExecutingAssembly());

            // Hand-written, and staying that way.
            Assert.IsTrue(OntologyDiscovery.Namespaces.ContainsKey("rdf"), "hand-written 'rdf'");
            Assert.IsTrue(OntologyDiscovery.Namespaces.ContainsKey("nco"), "hand-written 'nco'");

            // Generated by trinity-vocab from dces.ttl and owl.n3.
            Assert.IsTrue(OntologyDiscovery.Namespaces.ContainsKey("dces"), "generated 'dces'");
            Assert.IsTrue(OntologyDiscovery.Namespaces.ContainsKey("owl"), "generated 'owl'");

            Assert.AreEqual("http://www.w3.org/2002/07/owl#",
                OntologyDiscovery.Namespaces["owl"].OriginalString);

            // The hand-written 'dc' and the generated 'dces' describe the same namespace with the same
            // terms, which is the clearest statement that the two routes are equivalent.
            Assert.AreEqual(OntologyDiscovery.Namespaces["dc"].OriginalString,
                OntologyDiscovery.Namespaces["dces"].OriginalString,
                "The hand-written and generated Dublin Core vocabularies cover the same namespace.");
        }
    }
}
